# This is only an example. Most values are dummy placeholders just to match the
# types; they are often not optimal and must be tuned.

[control]
version = 4

state_file = 'mortal.pth'
best_state_file = 'baseline.pth'
tensorboard_dir = 'tensorboard'

device = 'auto'
enable_cudnn_benchmark = false
enable_amp = false
enable_compile = false

batch_size = 64
opt_step_every = 1

log_every = 40

# using env `TRAIN_PLAY_PROFILE`
[train_play.default]
games = 800
log_dir = 'train_play_logs'
boltzmann_epsilon = 0.005
boltzmann_temp = 0.05
top_p = 1.0
repeats = 1

[test_play]
games = 64
log_dir = 'test_play_logs'

[dataset]
globs = ['1v3_logs/*.json.gz']
file_index = 'file_index.pth'
file_batch_size = 15
reserve_ratio = 0.0
num_workers = 1
player_names_files = ['player_names.txt']
num_epochs = 3
enable_augmentation = false
augmented_first = false

[env]
gamma = 1
pts = [6.0, 4.0, 2.0, 0.0]

[resnet]
conv_channels = 192
num_blocks = 40

[cql]
min_q_weight = 5

[freeze_bn]
mortal = false

[optim]
eps = 1e-8
betas = [0.9, 0.999]
weight_decay = 0.1
max_grad_norm = 0

[optim.scheduler]
peak = 1e-4
final = 1e-4
warm_up_steps = 0
max_steps = 0

[baseline.train]
device = 'auto'
enable_compile = false
state_file = 'baseline.pth'

[baseline.test]
device = 'auto'
enable_compile = false
state_file = 'baseline.pth'

[1v3]
seed_key = -1
games_per_iter = 128
iters = 1
log_dir = '1v3_logs'

[1v3.challenger]
device = 'auto'
name = 'trainee'
state_file = 'mortal.pth'
stochastic_latent = false
enable_compile = false
enable_amp = true
enable_rule_based_agari_guard = true

[1v3.champion]
device = 'auto'
name = 'baseline'
state_file = 'baseline.pth'
stochastic_latent = false
enable_compile = false
enable_amp = true
enable_rule_based_agari_guard = true

[loop]
iterations = 0
eval_threshold = 0.5
eval_games = 64
start_from_baseline = false
max_logs = 640

[loop.exploration]
epsilon_initial = 0.10
epsilon_final = 0.05
temp_initial = 0.5
temp_final = 0.2
decay_iters = 20
